### ISSUE TITLE
Problem while parsing the training data

### ISSUE THREAD

**Issue by Srijita173** [thomasneff/Generative-Adversarial-Network-based-Synthesis-for-Supervised-Medical-Image-Segmentation#4]
[[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

I have tried changing the paths respectively

idlist_img_name = "list_of_img_ids.txt"
  idlist_seg_name = "list_of_seg_ids.txt"
  img_folder_path = "/home/nikhitha/Srijita_work/GAN/image_folder/images"
  seg_folder_path = "/home/nikhitha/Srijita_work/GAN/segmentation_folder/masks"

the text files are kept in the folder GAN where the train.py file is also kept.

list_of_img_ids.txt is written in the following way 

1.png
2.png
3.png
4.png
5.png
6.png
7.png
8.png

...
....

Can you please provide me with the solution to this problem , @jeya-maria-jose it will of great help if you also provide me some insights on this .

Thankyou in Advance .

**Comment by jeya-maria-jose** [comment]
Include a '/' at the end of your directory name !
Use this :
``` 
img_folder_path = "/home/nikhitha/Srijita_work/GAN/image_folder/images/"
seg_folder_path = "/home/nikhitha/Srijita_work/GAN/segmentation_folder/masks/"
```

**Comment by Srijita173** [comment]
Thankyou so much @jeya-maria-jose  , I just missed that ...
