### ISSUE TITLE
event logs and pytorch 

### ISSUE THREAD

**Issue by Ng-ms** [thomasneff/Generative-Adversarial-Network-based-Synthesis-for-Supervised-Medical-Image-Segmentation#8]
tf.app.flags.DEFINE_string('train_dir', '/tmp/dcgan_train',
                           """Directory where to write event logs """
                           """and checkpoint.""")
tf.app.flags.DEFINE_integer('max_steps', 100000,
                            """Number of batches to run.""")
tf.app.flags.DEFINE_boolean('log_device_placement', False,
                            """Whether to log device placement.""")

tf.app.flags.DEFINE_string("working_directory", "working_dir", "")
tf.app.flags.DEFINE_string("checkpoint_dir", "checkpoints", "")

can you please tell me what kind of files i should put here, i am not familiar with tf 
 and what is the possibility to converst the model to pytorch ?

**Comment by thomasneff** [comment]
Hi,

all of those are command line arguments with default values. 

If I remember correctly, only `working_directory` and `checkpoint_dir` are used in the code - the rest stems from the initial codebase of DCGAN.

`working_directory` is simply your "base output folder" which will be created and wherein all the output files and folders reside.

`checkpoint_dir` is the specific directory inside `working_directory` where the training checkpoints will be written to.

Sorry, I will not convert this model to pytorch.

**Comment by Ng-ms** [comment]
thank you for your answer 
i am having the same problems as the other's had 

OutOfRangeError (see above for traceback): RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[node shuffle_batch (defined at <ipython-input-3-0a63de529f41>:84) ]]

i tried the suggested solutions and delete the path for .txt file and just put the name, this error rise
idlist_img_name = 'imagetxt.txt'
idlist_seg_name = 'labeltext.txt'
IOError: [Errno 2] No such file or directory: 'imagetxt.txt'
what did you do to make it work
